### PR TITLE
Apiprocess syncs with new data entries

### PR DESCRIPTION
**Pull request by sohyeonlee**
I was able to force sync a data set with new entries from admin dashboard and see it updated in CartoDB's map. Have tested it few times with the admin page, but let me know if issues arise.

### CODE REVIEW

**Comment by sohyeonlee** [comment]
#59

**Comment by calo1** [comment]
@sohyeonlee @stlim0730 

Getting the following error upon add attempt:
screen shot 2016-07-29 at 11 51 49 am

**Comment by calo1** [comment]
@sohyeonlee @stlim0730 :  It looks like the dropbox file has  a name mismatch OR the api_process isnt sending a new version to the dropbox

**Comment by calo1** [comment]
Create new

**Comment by sohyeonlee** [comment]
there was one place where I forgot to change the names from new_data_point to data_point. I have pushed the changed version.

**Comment by stlim0730** [comment]
@sohyeonlee, thanks for the prompt response!
@calo1, the new one's deployed before being merged for test. Take a look and let me know: http://farmview.herokuapp.com/

**Comment by calo1** [comment]
This works on my end ... because Irene and I are both testing its hard to see if the redundancy problem has been fixed BUT running "force sync" on the appropriate upload brings new data .. the 15 minute delay is really problematic for testing .. but fine for the application in most other circumstances.  The next step is to replace the current survey data with the synced tables via api_process.  During this stage only I should be editing tables in CARTO.

**Comment by calo1** [comment]
@sohyeonlee @stlim0730 : see above comment and please merge

**Comment by calo1** [comment]
@stlim0730 I made the changes to CARTO ... and now the map page is not rendering anything

following error in console:  `(index):1110 Uncaught TypeError: Cannot read property 'layers' of undefined`

**Comment by calo1** [comment]
@stlim0730 : 

Hmm its working now ... I changed permission settings of the new layers from private to public ... so I think that solved it.  I should test with intermediate security .. which is "only with the link ... right now I'll leave it this way for the conference

**Pull request merged**
