### PR TITLE
Proximity queries

### PR DESCRIPTION
**Pull request by brianashpugh**
Location Proximity Queries: This adds the ability to query the parcel data layer for proximity to a specified location. It works by hitting the CartoDB street-level geocoding API to get the geolocation of an address (or city, etc.), then uses PostGIS functions to filter on the distance to the location. This required adding a new datafield for accessing the 'the_geom' field in the parcel table. the_geom encodes the parcel's geometry. To add the datafield for good, the deployment db snapshot had to be regenerated after the datafield was added in the admin terminal.

### CODE REVIEW

**Comment by brianashpugh** [comment]
@stlim0730 let me know if you want to take a look at this one.

**Comment by stlim0730** [comment]
Nice!
+1 for using existing query UI and another +1 for comments about environment dependencies.

**Comment by brianashpugh** [comment]
@calo1 I deployed it, but I misunderstood how our provision script is used. I imagined it was run on each deployment but that's wrong (which makes sense, because there's no reason to restart the machine for deployment!). I added the new datafield to the db backup in the repo thinking that would get the datafield into production, but we never run the provision script during deployment so it didn't. All I need to do is add the field in the admin console.

Strangely, the way we do things means you have to make db changes (e.g. adding a datafield) both in the test environment db backup (which we read for test env provisioning) and in the production admin console. 

My first response was fear that the backup and production dbs get out of sync. We should probably make sure there's some sort of db backup functionality through Heroku Postgres in case we catastrophically screw up the db, but we don't need to rely on the test db for that.

**Comment by ShaunGLIDE** [comment]
@brianashpugh, I just posted a message about provision on Slack to clarify how the script is used.

**Comment by stlim0730** [comment]
@brianashpugh, I just posted a message about provision on Slack to clarify how the script is used.

**Pull request merged**
